### ISSUE TITLE
uVision library missing header files

### ISSUE THREAD

**Issue by tmaltesen** [IOsonata/IOsonata#1]
Testing if I am able to build the new uVision library. It seems that there are some files missing, are you missing to commit them?

**agm_invn_icm20948.cpp** contains references to "Devices/Drivers/Icm20948/Icm20948...." that does not exists, the same goes for **imu_invn_icm20948.cpp**
Assume these can simply be removed from the library.

**Comment by hnhoan** [comment]
Some sensors such as the invensense and the Bosch BME680 require external library provided by the silicon vendor.  In the README.md, I explained where to download those libs and where to put them in the source folder tree for compiling.  Please follow the folder tree organization to compile. You can also disable compilation for those sensors if not require.

**Comment by tmaltesen** [comment]
OK, seems a little complicated to include different sensors in the same libary as more generic utilities. And then having to install build code for some not related. But anyway I will remove in my build.
