### ISSUE TITLE
problem building IOsonta nrf51

### ISSUE THREAD

**Issue by SoniaZotz** [IOsonata/IOsonata#10]
13:49:23 **** Incremental Build of configuration Debug for project IOsonata_nRF51 ****
make all 
make: *** No rule to make target 'Z:/your_root/external/nRF5_SDK/components/proprietary_rf/esb/nrf_esb.c', needed by 'src/nRF5_SDK/proprietary_rf/esb/nrf_esb.o'.  Stop.

13:49:24 Build Finished (took 1s.578ms)

**Comment by hnhoan** [comment]
Have you installed the Nordic SDK as specified in the REAME.md ?  I don't think we have ESB in the nRF51 target example.  For more instructions you can follow these blogs.
https://www.i-syst.com/article/eclipse-ide-firmware-development-iosonata
https://embeddedsoftdev.blogspot.com/p/ehal-nrf51.html

**Comment by SoniaZotz** [comment]
![image](https://user-images.githubusercontent.com/10633874/148145613-56888da1-f4c4-4bb6-a34b-dd223e557436.png)

**Comment by SoniaZotz** [comment]
![image](https://user-images.githubusercontent.com/10633874/148145926-1967fe45-a0c7-497d-9f08-30156dc020dd.png)

**Comment by hnhoan** [comment]
To compile nRF51 you need to name the SDK12 as nRF5_SDK_12
nRF5_SDK is for SDK17

**Comment by hnhoan** [comment]
Releated to #9
