### ISSUE TITLE
'.syntax divided' arm assembly not supported

### ISSUE THREAD

**Issue by SoniaZotz** [IOsonata/IOsonata#11]
#if defined ( __ARMCC_VERSION )
#elif defined ( __GNUC__ )
		".syntax divided\n"

@file	idelay.h

**Comment by hnhoan** [comment]
Which compiler and which version are you using ? This is GCC syntax.

**Comment by SoniaZotz** [comment]
![image](https://user-images.githubusercontent.com/10633874/153787002-d0f6a63f-9027-4bc2-b4a1-22c3068fdffc.png)

**Comment by SoniaZotz** [comment]
![Snag_4b4a836](https://user-images.githubusercontent.com/10633874/153787060-f8c4c3a0-fc51-4ec4-a732-28f749ee2d50.png)

**Comment by hnhoan** [comment]
Segger studio is not recommended see README.md.  It does not support C++.  It stripped down GCC that won't compile IOsonata.  To use Segger Studio, you need to set it to use external full GCC.

Follow this blog to use Eclipse GCC. https://www.i-syst.com/article/eclipse-ide-firmware-development-iosonata

**Comment by SoniaZotz** [comment]
ok thanks
