### ISSUE TITLE
interupts Blinky nrf51 - not working why are INTENSET and INTENCLR  set at the same time ?

### ISSUE THREAD

**Issue by SoniaZotz** [IOsonata/IOsonata#13]
![int52](https://user-images.githubusercontent.com/10633874/155403496-92d43cee-ca8b-4041-b266-ea5a0418b11c.jpg)

**Comment by hnhoan** [comment]
What exactly is the problem ? Did you get the interrupt when you pressed the button ?

**Comment by hnhoan** [comment]
Have you check the data sheet as to what those registers should give you when you read it ? Those registered are for writing.  You write 1 to the SET register to set and write 1 to CLR register to clear.

**Comment by SoniaZotz** [comment]
still no interrupts - have no idea --LOST  using PCA10040 


![image](https://user-images.githubusercontent.com/10633874/155803223-8539a742-a0cd-4acd-9ae0-4c1c52fbdb24.png)
![image](https://user-images.githubusercontent.com/10633874/155803273-3aaa9d0c-eec1-4f69-b4a2-21d5226deb4e.png)
![image](https://user-images.githubusercontent.com/10633874/155803299-ded1ee81-d587-4b45-9d46-9e8d745ee417.png)

**Comment by hnhoan** [comment]
PCA10040 is nRF52832 (nRF52 series) not nRF51 series.  You are using the wrong MCU.

**Comment by SoniaZotz** [comment]
https://www.keil.com/boards2/nordicsemiconductors/nrf52pca10040/

**Comment by SoniaZotz** [comment]
![image](https://user-images.githubusercontent.com/10633874/155814693-53c258e9-fb08-42af-a4a7-6e254779663a.png)

**Comment by SoniaZotz** [comment]
I gave up on the nRF51 series , thought I would progress  I also have the same problem with the BLE400 boards which are NRF51822  still struggling with your IOSONATA  I thought it would be easy , however it not the case for me

**Comment by hnhoan** [comment]
You to open the Blinky project from the nRF52832 folder.  You got everything now.  Just open project in the target folder and change the Pin map to your board.  I work every day with the nRF52 series so all everything should be up to date.  The nRF51 series is discontinued so I don't update it as often.

**Comment by SoniaZotz** [comment]
still not working - would you please check the app in your side with the file that are on Git hub using the PCA10040 DK

**Comment by hnhoan** [comment]
In the board.h make sure the resistor settings is PULLUP

#define BUTTON_PINS_MAP		{ \
	{BUT1_PORT, BUT1_PIN, BUT1_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
	{BUT2_PORT, BUT2_PIN, BUT2_PINOP, IOPINDIR_INPUT, IOPINRES_PULLUP, IOPINTYPE_NORMAL}, \
}
