### ISSUE TITLE
Interfacing two development kits

### ISSUE THREAD

**Issue by eyueldev-tech** [IOsonata/IOsonata#14]
Hi, 
I wanted to interface Invensense ICM 20948 Development Kit with nRF5340 kit to send it with bluetooth.
is it possible with Iosonata source code? any pointers would be appreciated.
Thanks

**Comment by hnhoan** [comment]
The I2C & SPI drivers are available for the nRF5340 and so all the sensors in IOsonata.  Unfortunately there is no port available yet for Bluetooth.  nRFConnectSDK is a big blob that is difficult to extract but it is in our plan to do so.  However it is possible to prioritize it with fee based development. Extracting Bluetooth stack from nRFConnectSDK is a huge task.

**Comment by Eyuel-Military-Project** [comment]
Thanks for explaining it. noted
