### ISSUE TITLE
Assembler code does not compile with ARM compiler

### ISSUE THREAD

**Issue by tmaltesen** [IOsonata/IOsonata#2]
The module pulse_train.cpp include a files idelay.h which includes assembler code.
This assembler code does not compile with Arm Compiler 6.
Not sure when pulse_train.cpp is needed, but removing it from the library build solves the problem.

**Comment by hnhoan** [comment]
I already fixed the idelay.h to compile with uVision5 compiler v6

**Comment by tmaltesen** [comment]
Current version (as of now) does not compile.
Example idelay.h line 59-60

static inline __attribute__((always_inline)) void usDelay(uint32_t cnt) {
	asm volatile (

../../../../../include\idelay.h(60): error: use of undeclared identifier 'asm'
        asm volatile (

**Comment by hnhoan** [comment]
I compiled it yesterday.  There is a preliminary uVision lib project in the nRF52832.  Can you try it and look at the settings.  gnuC11 and gnuC++11 need to be selected.

**Comment by tmaltesen** [comment]
Thats the one I am using.
I have also tried with regular C11 and C++11.

**Comment by tmaltesen** [comment]
I have copied it to the nRF52840 directory and modified it for this CPU including system files. 
If I remove pulse_train.c I can build (I have also removed most sensor device specific files)

**Comment by tmaltesen** [comment]
Aaahhh - it is only release version that does not build. Debug configuration does build. Has not figured out why.

**Comment by hnhoan** [comment]
weird, I compiled both release and debug before pushing them.  Could there be a missing setting in your release build ?

**Comment by tmaltesen** [comment]
You are absolutely right about compiler version!
It needs GNU for just that assembler code in idelay.h.
I was messing with gnu / not gnu and was switching between release and debug. So it's fine
