### ISSUE TITLE
Missing header files for tphg_bme680.cpp

### ISSUE THREAD

**Issue by tmaltesen** [IOsonata/IOsonata#3]
The file tphg_bme680.cpp is unable to compile because of missing header file in line 91
#include "bsec_interface.h"

**Comment by hnhoan** [comment]
Some sensors such as the invensense and the Bosch BME680 require external library provided by the silicon vendor.  In the README.md, I explained where to download those libs and where to put them in the source folder tree for compiling.  Please follow the folder tree organization to compile. You can also disable compilation for those sensors if not require.

**Comment by tmaltesen** [comment]
OK, seems a little complicated to include different sensors in the same libary as more generic utilities. And then having to install build code for some not related. But anyway I will remove in my build.
