### ISSUE TITLE
Recommendation for use

### ISSUE THREAD

**Issue by tmaltesen** [IOsonata/IOsonata#4]
Do you have a recommendation for how to use the code....
Assume I want to use the uart_nrf5x.cpp module, what is propsed way of including it in a main project.

There are a lot of directory levels and especially include file levels needed. 

Do you suggest to copy the hole directory structure and insert into project the files from different locations. Also adding all include directories to the main project.
Or
Would it be better to have a library, and then all include levels are still needed in main project.
Or 
Any other suggestion?

**Comment by hnhoan** [comment]
There are usage example in IOsonata/exemples/uart.  
The way the folder layer is structured is because the multi-platform supports.  The top layer are generic to all, the deeper you go are the implementations for a specific platform.

**Comment by tmaltesen** [comment]
Ok - maybe I did not make it clear. It was not code use but more how you suggest to include you libarry files into a main project. Source, includes etc. 
If I just pick the source (uart_nrf5x.cpp) and include it in my project, there will be a number of things missing. So more looking for an advise on how you were thinking it should be used.

**Comment by hnhoan** [comment]
yes, you can cherry pick what you need and add links to your project and set the paths to the lib folders.  There are generic statup code and interrupt vectors for each target.  Normally I have it for build by platform.  I haven't done for uVision yet.  You can use the default uVision, just make sure to change the interrupt handling name for the uart to match with the vector.
