### ISSUE TITLE
problem cpmpiling blinky 

### ISSUE THREAD

**Issue by SoniaZotz** [IOsonata/IOsonata#9]
cannot find entry symbol ResetEntry; defaulting to 00000410

is there an an arm startup .s file that is missing

**Comment by hnhoan** [comment]
It is in the library.  Which target are you working with ? You need to compile the library for the target you are using.  Please follow installation instruction in the MREADME.md

**Comment by SoniaZotz** [comment]
nRF5SDK110089a8197 all kinds of errors - been at this for over a week and still cannot build cleanly the IOsontata distributions 

which version  of the nFE SDK do you recommend ?

**Comment by hnhoan** [comment]
For nRF52, SDK12.3
For nRF52, SDK17.1

**Comment by SoniaZotz** [comment]
**almost there for the most part , but**  

from Blinky  -- cannot find -lIOsonata_nRF51


**because  >>>>**

from  IOsonata_nRF51  --- Invalid project path: Include path not found (Z:\your_root\external\nRF5_SDK_12\components\ble\ble_services\common).

**Comment by SoniaZotz** [comment]
![image](https://user-images.githubusercontent.com/10633874/148171370-f5989afd-c11b-4c96-a69f-1275112a5849.png)

**Comment by SoniaZotz** [comment]
![image](https://user-images.githubusercontent.com/10633874/148171518-43d7df23-af9a-4b3f-9212-03f25b50b625.png)

**Comment by hnhoan** [comment]
Not sure what is wrong on your side but I compile just fine.  Try a new workspace and open the projects from folder Nordic/nRF51 again.  Here is my eclipse screenshot

<img width="1678" alt="Screen Shot 2022-01-05 at 5 37 23 AM" src="https://user-images.githubusercontent.com/6577947/148204268-72945cfb-0f78-4bee-90dc-64f5b7fef9c8.png">

**Comment by SoniaZotz** [comment]
### **thank you for your help** 
it was the --> 
 {                                                     \
    __asm(                                              \
        "svc %0\n"                                      \
        "bx r14" : : "I" ((uint16_t)number) : "r0"      \
    );                                                  \
  } 


Invoking: Cross ARM GNU Create Flash Image
arm-none-eabi-objcopy -O ihex "Blinky.elf"  "Blinky.hex"
Finished building: Blinky.hex
 
Invoking: Cross ARM GNU Print Size
arm-none-eabi-size --format=berkeley "Blinky.elf"
   text	   data	    bss	    dec	    hex	filename
   7235	   1272	    304	   8811	   226b	Blinky.elf
Finished building: Blinky.siz


_now onward - byte by byte_

**Comment by hnhoan** [comment]
Yes there is a section on the blog page about that bug in the SDK.
<img width="1171" alt="Screen Shot 2022-01-05 at 4 28 44 PM" src="https://user-images.githubusercontent.com/6577947/148292154-ea318e41-4660-4b1b-8a8b-9eee52ad442a.png">
